version: '3'

services:

  some-rabbit:
    image: rabbitmq:3.7.16-management
    hostname: some-hostname
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "rabbitmq-persistence:/var/lib/rabbitmq"

  some-redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  rabbitmq-persistence: